package com.poc.neo4j.dao;

public interface Constants {
	
	String AT_CLASS = "@Class";
	String METHOD_NOT_FOUND = "METHOD_NOT_FOUND";
	String ERROR_ACCESSING_METHOD= "ERROR_ACCESSING_METHOD";
	String ERROR_INVOKING_SETPROPERTY_METHOD= "ERROR_INVOKING_SETPROPERTY_METHOD";
	String CLASS_NOT_FOUND = "CLASS_NOT_FOUND";
	String ERROR_IN_INSTANTIATION = "ERROR_IN_INSTANTIATION";
}
